version: '3.7'

services:

  powergate:
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - lotus
    environment:
      - POWD_DEVNET=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    restart: unless-stopped

  ipfs:
    ports:
      - 5001:5001

  lotus:
    image: textile/lotus-devnet:ntwk-butterfly-v7.20.0
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=1500
      - TEXLOTUSDEVNET_BIGSECTORS=${BIGSECTORS}
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
